### ISSUE TITLE
Example Constraints Violating CIS Benchmark

### ISSUE THREAD

**Issue by almokhtar-alelewi** [avolens/kubefuzz#1]
**Overview:**
create an example set of constraints that violate the CIS (Center for Internet Security) benchmark for Kubernetes. The purpose is to leverage these constraints within the fuzzing tool to generate resources that simulate non-compliant Pods.

**Objective:**
define a set of constraints that are considered "very bad" according to the CIS benchmark. These constraints will be used by the fuzzing tool to generate resources that test the resiliency and security of the Kubernetes admission controller.

**Proposed Constraints:**
To initiate the discussion, I propose the following example constraints that are expected to violate the CIS benchmark:

1. **AllowPrivilegeEscalation: true**
2. **HostIPC: true** 
3. **HostNetwork: true** 
4. **HostPID: true** 
5. **AllowPrivileged: true** 
6. **Privileged: true** 
or more ..

**Comment by p4ck3t0** [comment]
Hi @aasyria,

We are currently working on adding constrain files for sample Benchmarks, like CIS. I will ping you once we added these constrains.

**Comment by p4ck3t0** [comment]
We will use CIS Kubernetes V1.24 for the first Implementation.

**Comment by 7unn3l** [comment]
Hello @aasyria,

That's a great idea :) I've added a sample pod CIS 1.24 constraints on the main branch directly. Feel free to open a pull request to add some of your own!

**Comment by almokhtar-alelewi** [comment]
thanx
